# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - chat-app-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Змінено на стабільнішу LTS версію (18.x)

      - name: Navigate to frontend directory
        run: cd chat-app-client  # Змінено: перехід до директорії фронтенду

      - name: npm install and build
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'  # Додано для вирішення проблем з OpenSSL
        run: |
          cd chat-app-client  # Потрібно повторити, оскільки 'cd' на попередньому кроці не зберігається між кроками
          npm install
          npm run build --if-present
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: chat-app-client/build  # Змінено: шлях до збірки React-додатку

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Create web.config for Azure
        run: |
          echo '<?xml version="1.0"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="React Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                      <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                  </rule>
                </rules>
              </rewrite>
              <staticContent>
                <mimeMap fileExtension=".json" mimeType="application/json" />
              </staticContent>
            </system.webServer>
          </configuration>' > web.config

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'chat-app-frontend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_d03c5b4b2b714d97b3f97fe68a25d972 }}